name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SSH Connect 
      run: |
        eval `ssh-agent`
        mkdir ~/.ssh && chmod 700 ~/.ssh
        touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys
        echo "${{ secrets.EC2 }}" > ~/key.pem
        ssh -i '~/key.pem' ubuntu@ec2-18-220-255-197.us-east-2.compute.amazonaws.com
