name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SSH Connect 
      run: |
        mkdir -p ~/.ssh 
        echo "${{ secrets.EC2 }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa && chmod 700 ~/.ssh 
        ssh -tt '~/.ssh/id_rsa' ubuntu@ec2-18-220-255-197.us-east-2.compute.amazonaws.com
