name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SSH Connect 
      run: |
        mkdir -p ~/.ssh 
        echo "${{ secrets.EC2 }}" > ~/key.pem 
        chmod 700 ~/.ssh 
        ssh -tt '~/key.pem' ubuntu@ec2-18-220-255-197.us-east-2.compute.amazonaws.com
