name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SSH Connect 
      run: |
        echo "${{ secrets.EC2 }}" > ~/key.pem
        chmod 400 ~/key.pem 
        ssh -t -i '~/key.pem' ubuntu@ec2-18-220-255-197.us-east-2.compute.amazonaws.com
