name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     -  name: OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            echo "hello push" > ~/hello.txt
          host: ${{ secrets.EC2_HOST }}
          user: ubuntu
          key: ${{ secrets.EC2}}
          args: "-tt -vvv"
