name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH-Agent
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: |
          ${{ secrets.EC2 }}
      run: ssh -t -t ubuntu@ec2-18-220-255-197.us-east-2.compute.amazonaws.com
      
